In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

E = np.array([[1,2,3,4],[3,3,3,3],[2,4,6,8]])
F = np.array([[4,9,16,10],[3,3,3,3],[1,2,3,5]])

print ("E:\n",E)
print ("F:\n",F)
f = np.array([[.25,.5,.75,.5],[.01,.02,.03,.04],[.01,.01,.01,.01]])
print ("f:\n",f)
print ("E+F:\n",E+F)
print ("E-F:\n",E-F)
print ("E*F:\n",E*F)
print("---")
df = np.diff(E)
print("np.diff(f):\n",df)

E:
 [[1 2 3 4]
 [3 3 3 3]
 [2 4 6 8]]
F:
 [[ 4  9 16 10]
 [ 3  3  3  3]
 [ 1  2  3  5]]
f:
 [[0.25 0.5  0.75 0.5 ]
 [0.01 0.02 0.03 0.04]
 [0.01 0.01 0.01 0.01]]
E+F:
 [[ 5 11 19 14]
 [ 6  6  6  6]
 [ 3  6  9 13]]
E-F:
 [[ -3  -7 -13  -6]
 [  0   0   0   0]
 [  1   2   3   3]]
E*F:
 [[ 4 18 48 40]
 [ 9  9  9  9]
 [ 2  8 18 40]]
---
np.diff(f):
 [[1 1 1]
 [0 0 0]
 [2 2 2]]


In [2]:
notfirst = E[:,1:]
notlast  = E[:,:-1]
Emid = .5*(notlast + notfirst)
print("Emid:\n",Emid)

Emid:
 [[1.5 2.5 3.5]
 [3.  3.  3. ]
 [3.  5.  7. ]]


In [3]:
# testing and learning
a = np.arange(12).reshape(4,3)
G = E*F
print("G:\n",G)
gsum = G.sum(axis=1)
print("Array row axis summaries:\n",gsum)

#gsumsquared = np.square(gsum)
#print("Row totals squared:\n",gsumsquared)

rooted = np.sqrt(gsum)
print("square root of the row totals:\n",rooted)

G:
 [[ 4 18 48 40]
 [ 9  9  9  9]
 [ 2  8 18 40]]
Array row axis summaries:
 [110  36  68]
square root of the row totals:
 [10.48808848  6.          8.24621125]


In [4]:
product = (E*F)
SWH = 4*np.sqrt(product.sum(axis=1))
print("significant wave height:\n",SWH)

significant wave height:
 [41.95235393 24.         32.984845  ]


In [9]:
PE = 1./Emid
print("PE:\n",PE)

PE:
 [[0.66666667 0.4        0.28571429]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.2        0.14285714]]
