In [13]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

E = np.array([[1,2,3,4],[3,3,3,3],[2,4,6,8]])
F = np.array([[.5,1,2,3],[.5,1,1,2],[.5,1,2,2]])

print ("E:\n",E)
print ("F:\n",F)
f = np.array([[.25,.5,.75,.5,1,3,5,7,9],[.1,.2,.3,.4,1,3,5,7,9],[.1,.1,.1,.1,1,3,5,7,9]])
print ("f:\n",f)
print ("E+F:\n",E+F)
print ("E-F:\n",E-F)
print ("E*F:\n",E*F)
print("---")
df = np.diff(f)
print("np.diff(f):\n",df)

E:
 [[1 2 3 4]
 [3 3 3 3]
 [2 4 6 8]]
F:
 [[0.5 1.  2.  3. ]
 [0.5 1.  1.  2. ]
 [0.5 1.  2.  2. ]]
f:
 [[0.25 0.5  0.75 0.5  1.   3.   5.   7.   9.  ]
 [0.1  0.2  0.3  0.4  1.   3.   5.   7.   9.  ]
 [0.1  0.1  0.1  0.1  1.   3.   5.   7.   9.  ]]
E+F:
 [[ 1.5  3.   5.   7. ]
 [ 3.5  4.   4.   5. ]
 [ 2.5  5.   8.  10. ]]
E-F:
 [[0.5 1.  1.  1. ]
 [2.5 2.  2.  1. ]
 [1.5 3.  4.  6. ]]
E*F:
 [[ 0.5  2.   6.  12. ]
 [ 1.5  3.   3.   6. ]
 [ 1.   4.  12.  16. ]]
---
np.diff(f):
 [[ 0.25  0.25 -0.25  0.5   2.    2.    2.    2.  ]
 [ 0.1   0.1   0.1   0.6   2.    2.    2.    2.  ]
 [ 0.    0.    0.    0.9   2.    2.    2.    2.  ]]


In [14]:
notfirst = E[:,1:]
notlast  = E[:,:-1]
Emid = .5*(notlast + notfirst)
print("Emid:\n",Emid)

Emid:
 [[1.5 2.5 3.5]
 [3.  3.  3. ]
 [3.  5.  7. ]]


In [15]:
# testing and learning
a = np.arange(12).reshape(4,3)
G = E*F
print("G:\n",G)
gsum = G.sum(axis=1)
print("Array row axis summaries:\n",gsum)

#gsumsquared = np.square(gsum)
#print("Row totals squared:\n",gsumsquared)

rooted = np.sqrt(gsum)
print("square root of the row totals:\n",rooted)

G:
 [[ 0.5  2.   6.  12. ]
 [ 1.5  3.   3.   6. ]
 [ 1.   4.  12.  16. ]]
Array row axis summaries:
 [20.5 13.5 33. ]
square root of the row totals:
 [4.52769257 3.67423461 5.74456265]


In [16]:
product = (E*F)
SWH = 4*np.sqrt(product.sum(axis=1))
print("significant wave height:\n",SWH)

significant wave height:
 [18.11077028 14.69693846 22.97825059]


In [17]:
PE = 1./Emid
print("PE:\n",PE)

PE:
 [[0.66666667 0.4        0.28571429]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.2        0.14285714]]


In [18]:
print('frequencies:\n',f)
notfirst = f[:,1:]       # every element in a row, except for the first
notlast  = f[:,:-1]      # every element in a row, except for the last
fmid = .5*(notfirst + notlast)
print('frequency mid-points:\n',fmid)
p = np.array([0,5,7,9,11,13,15,17,19,21,35])
print('periods:',p)

notfirst = p[1:]       # every element in a row, except for the first
notlast  = p[:-1]      # every element in a row, except for the last
pmid = .5*(notfirst + notlast)
print('period mid-points:',pmid)

pf = 1./fmid[1]
print('wave frequency periods:',pf)

frequencies:
 [[0.25 0.5  0.75 0.5  1.   3.   5.   7.   9.  ]
 [0.1  0.2  0.3  0.4  1.   3.   5.   7.   9.  ]
 [0.1  0.1  0.1  0.1  1.   3.   5.   7.   9.  ]]
frequency mid-points:
 [[0.375 0.625 0.625 0.75  2.    4.    6.    8.   ]
 [0.15  0.25  0.35  0.7   2.    4.    6.    8.   ]
 [0.1   0.1   0.1   0.55  2.    4.    6.    8.   ]]
periods: [ 0  5  7  9 11 13 15 17 19 21 35]
period mid-points: [ 2.5  6.   8.  10.  12.  14.  16.  18.  20.  28. ]
wave frequency periods: [6.66666667 4.         2.85714286 1.42857143 0.5        0.25
 0.16666667 0.125     ]


In [19]:
pf

array([6.66666667, 4.        , 2.85714286, 1.42857143, 0.5       ,
       0.25      , 0.16666667, 0.125     ])

In [20]:
pf[(pf>3) &(pf <=6)]


array([4.])

In [21]:
for idx,_ in enumerate(pmid):
    print(idx)

0
1
2
3
4
5
6
7
8
9


In [ ]:
import matplotlib.pyplot as plt
from matplotlib import colors
import numpy as np

data = np.random.rand(10, 10) * 20

#print(type(data),data)

# create discrete colormap
cmap = colors.ListedColormap(['red', 'blue'])
bounds = [0,10,20]
norm = colors.BoundaryNorm(bounds, cmap.N)

fig, ax = plt.subplots()
ax.imshow(data, cmap=cmap, norm=norm)

# draw gridlines
ax.grid(which='major', axis='both', linestyle='-', color='k', linewidth=2)
ax.set_xticks(np.arange(-.5, 10, 1));
ax.set_yticks(np.arange(-.5, 10, 1));

plt.show()