In [11]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

E = np.array([[1,2,3,4],[3,3,3,3],[2,4,6,8]])
F = np.array([[.5,1,2,3],[.5,1,1,2],[.5,1,2,2]])

print ("E:\n",E)
print ("F:\n",F)
f = np.array([[.25,.5,.75,.5],[.1,.2,.3,.4],[.1,.1,.1,.1]])
print ("f:\n",f)
print ("E+F:\n",E+F)
print ("E-F:\n",E-F)
print ("E*F:\n",E*F)
print("---")
df = np.diff(f)
print("np.diff(f):\n",df)

E:
 [[1 2 3 4]
 [3 3 3 3]
 [2 4 6 8]]
F:
 [[ 0.5  1.   2.   3. ]
 [ 0.5  1.   1.   2. ]
 [ 0.5  1.   2.   2. ]]
f:
 [[ 0.25  0.5   0.75  0.5 ]
 [ 0.1   0.2   0.3   0.4 ]
 [ 0.1   0.1   0.1   0.1 ]]
E+F:
 [[  1.5   3.    5.    7. ]
 [  3.5   4.    4.    5. ]
 [  2.5   5.    8.   10. ]]
E-F:
 [[ 0.5  1.   1.   1. ]
 [ 2.5  2.   2.   1. ]
 [ 1.5  3.   4.   6. ]]
E*F:
 [[  0.5   2.    6.   12. ]
 [  1.5   3.    3.    6. ]
 [  1.    4.   12.   16. ]]
---
np.diff(f):
 [[ 0.25  0.25 -0.25]
 [ 0.1   0.1   0.1 ]
 [ 0.    0.    0.  ]]


In [12]:
notfirst = E[:,1:]
notlast  = E[:,:-1]
Emid = .5*(notlast + notfirst)
print("Emid:\n",Emid)

Emid:
 [[ 1.5  2.5  3.5]
 [ 3.   3.   3. ]
 [ 3.   5.   7. ]]


In [13]:
# testing and learning
a = np.arange(12).reshape(4,3)
G = E*F
print("G:\n",G)
gsum = G.sum(axis=1)
print("Array row axis summaries:\n",gsum)

#gsumsquared = np.square(gsum)
#print("Row totals squared:\n",gsumsquared)

rooted = np.sqrt(gsum)
print("square root of the row totals:\n",rooted)

G:
 [[  0.5   2.    6.   12. ]
 [  1.5   3.    3.    6. ]
 [  1.    4.   12.   16. ]]
Array row axis summaries:
 [ 20.5  13.5  33. ]
square root of the row totals:
 [ 4.52769257  3.67423461  5.74456265]


In [14]:
product = (E*F)
SWH = 4*np.sqrt(product.sum(axis=1))
print("significant wave height:\n",SWH)

significant wave height:
 [ 18.11077028  14.69693846  22.97825059]


In [15]:
PE = 1./Emid
print("PE:\n",PE)

PE:
 [[ 0.66666667  0.4         0.28571429]
 [ 0.33333333  0.33333333  0.33333333]
 [ 0.33333333  0.2         0.14285714]]


In [16]:
print('frequencies:\n',f)
notfirst = f[:,1:]       # every element in a row, except for the first
notlast  = f[:,:-1]      # every element in a row, except for the last
fmid = .5*(notfirst + notlast)
print('frequency mid-points:\n',fmid)
p = np.array([0,5,7,9,11,13,15,17,19,21,35])
print('periods:',p)

notfirst = p[1:]       # every element in a row, except for the first
notlast  = p[:-1]      # every element in a row, except for the last
pmid = .5*(notfirst + notlast)
print('period mid-points:',pmid)

pf = 1./fmid
print('wave frequency periods:',pf)

frequencies:
 [[ 0.25  0.5   0.75  0.5 ]
 [ 0.1   0.2   0.3   0.4 ]
 [ 0.1   0.1   0.1   0.1 ]]
frequency mid-points:
 [[ 0.375  0.625  0.625]
 [ 0.15   0.25   0.35 ]
 [ 0.1    0.1    0.1  ]]
periods: [ 0  5  7  9 11 13 15 17 19 21 35]
period mid-points: [  2.5   6.    8.   10.   12.   14.   16.   18.   20.   28. ]
wave frequency periods: [[  2.66666667   1.6          1.6       ]
 [  6.66666667   4.           2.85714286]
 [ 10.          10.          10.        ]]


In [17]:
pf

array([[  2.66666667,   1.6       ,   1.6       ],
       [  6.66666667,   4.        ,   2.85714286],
       [ 10.        ,  10.        ,  10.        ]])

In [26]:
mask = (pf > 1) & (pf <= 5)
mask

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False, False]], dtype=bool)

In [34]:
pf[(fmid >.1)&(fmid <=.5)]

array([ 2.66666667,  6.66666667,  4.        ,  2.85714286])

In [20]:
for idx,_ in enumerate(pmid):
    print(idx)

0
1
2
3
4
5
6
7
8
9
